fix(action.ts): do not freeze actions in dev mode
Hotell/rex-tils pull request #29
Opened 2019-01-15 03:26 UTC by navneet-g

fix #21

_If there is a linked issue, mention it here._

- [X] Bug
- [ ] Feature

## Requirements

- [X] Read the [contribution guidelines](./.github/CONTRIBUTING.md).
- [X] Wrote tests.
- [X] Updated docs and upgrade instructions, if necessary.

## Rationale

_Why is this PR necessary?_
Allows usage of the library with redux-saga or any other library that updates the action objects.

## Implementation
Removed Object.freeze in action.ts
_Why have you implemented it this way? Did you try any other methods?_

## Open questions

_Are there any open questions about this implementation that need answers?_

## Other
On my box I was not able to run all the tests, even in master branch. I get lot of build errors. But I belive these changes are enough to work, I will monitor the PR build to see if there are any issues.
 All the errors are in as follows
" src/__tests__/redux/rx-operators.spec.ts:3:24 - error TS1149: File name 'E:/rex-tils/src/redux/rx-operators.ts' differs from already included file name 'e:/rex-tils/src/redux/rx-operators.ts' only in casing."

2019-01-15 07:25 UTC, Hotell requested changes
Please revert those deleted tests and we can merge. Thanks a lot!

2019-01-15 07:25 UTC, Hotell commented on src/__tests__/redux/actions.spec.ts
> -  describe(`Should create immutable objects`, () => {
Please keep these tests, as they are still covering compile time immutability :) Action is `Readonly`. I don't wanna support that anyone can mutate action object directly. If some library does it under the hood, "fine" (one of the things why I don't use redux saga... and never will).

2019-01-15 08:16 UTC, Hotell commented on src/__tests__/redux/actions.spec.ts
> -  describe(`Should create immutable objects`, () => {
actually it needs to be updated to following:

```ts
describe(`Should create compile time only immutable objects`, () => {
    const SET_AGE = '[core] set age'
    const setAge = (age: number) => createAction(SET_AGE, age)
    const setAgeAction = setAge(33)

    // @ts-ignore
    expect(() => (setAgeAction.type = 'Foo')).not.toThrow()
    // @ts-ignore
    expect(() => (setAgeAction.payload = 44)).not.toThrow()
  })
```

2019-01-16 00:42 UTC, navneet-g commented on src/__tests__/redux/actions.spec.ts
> -  describe(`Should create immutable objects`, () => {
Thanks ... updated

2019-01-16 08:36 UTC, merged

2019-01-16 08:37 UTC, Hotell commented
thanks a lot @navneet-g! much appreciated! 👌🍻